### ISSUE TITLE
Doesn't not send reminders to holders of outstanding invoices to acountholders

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#13]
I notice that reminders of outstanding emails are sent to the wordpress admin however they are not being sent to the actual account holders themselves. How can we get invoice reminders to be sent to account holders?

**Comment by ole1986** [comment]
@tkembo have you made sure the test Mode is disabled?

![image](https://user-images.githubusercontent.com/4850116/69705481-f2842580-10f5-11ea-8f5f-332b89538f67.png)

**Comment by tawandakembo** [comment]
You're right. I had to disable test mode. Thank you
