### ISSUE TITLE
Deactivate unpaid accounts

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#14]
Can we add a feature that allows unpaid accounts to be automatically suspended.

**Comment by ole1986** [comment]
There is not yet and automated option available, but you can manually disable it from the "Invoice" meta box located in the related Woocommerce Order

![image](https://user-images.githubusercontent.com/4850116/69705937-dd5bc680-10f6-11ea-871c-5ade3291b9be.png)

**Comment by tawandakembo** [comment]
Thank you
