### ISSUE TITLE
Clicking on the pay invoice button in 'my account' takes you to a blank page

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#15]
When a customer logs into their account, clicks on the invoices link and attempts to pay an invoice, they are just taken to a page that as the invoice number and the order number. I expected them to be taken to a checkout page. This is the screen that is shown:

![image](https://user-images.githubusercontent.com/1892654/69787540-71945f00-11c5-11ea-9ed3-da585047053f.png)

**Comment by ole1986** [comment]
One reason could be that the order does not have a payment method selected.
Double check the Order billing information and fill in the payment method accordingly

![image](https://user-images.githubusercontent.com/4850116/69791625-3003b400-11c5-11ea-97f9-06d6082f2530.png)

**Comment by tawandakembo** [comment]
Even when I add a payment method, it still just mentions the payment method but doesn't allow you to proceed:

![image](https://user-images.githubusercontent.com/1892654/69805792-1b85e280-11ea-11ea-82f2-3252382f74c3.png)

**Comment by ole1986** [comment]
I am not familiar with payment method "paynow".
It has been tested with bacs and PayPal.

Need to figure out more about Paynow payment methods.
