### ISSUE TITLE
Update since Wordpress V5.2.5 throws errors in plugin.

### ISSUE THREAD

**Issue by lonerunner** [ole1986/wc-invoice-pdf#18]
Ever since i updated to new wordpress versions i get an error on plugin admin page.

I tested it from WP version 5.2.5 and up, there is an error:

> Fatal error: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /web/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php:120 Stack trace: #0 /web/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php(120): DateTimeZone->__construct('') #1 /web/wp-includes/class-wp-hook.php(286): WCInvoicePdf\Menu\InvoiceMenu->DisplayInvoices('') #2 /web/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /web/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /web/wp-admin/admin.php(253): do_action('wc-invoices_pag...') #5 {main} thrown in /web/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php on line 120

**Comment by ole1986** [comment]
What language is WordPress configured?

**Comment by ole1986** [comment]
Possible reason for this is that the related locale is unavailable to PHP.

https://stackoverflow.com/a/9325124/2106997

After installing additional locales a restart of PHP (Apache/nginx) may be necessary

**Comment by lonerunner** [comment]
I've checked and

Wordpress is on english language en_us

Default locale on server is on en_US.UTF-8 but it have other languages installed too.

I've checked phpinfo and it's using  php v7.1 with locale set on en_US.

I can't access with ssh on this server, i can only manage things through control panel.

**Comment by ole1986** [comment]
I am sorry. You might need to double check the timezone setting in WordPress
![image](https://user-images.githubusercontent.com/4850116/71740070-84045700-2e5b-11ea-9353-8775157d6c9e.png)

and compare it against the list of [supported timezones in PHP](https://www.php.net/manual/en/timezones.php)

**Comment by lonerunner** [comment]
Hmm, interesting. When i set timezone to UTC+1 in Wordpress it wont work, but when i set it to city like Europe/Amsterdam it works. I don't understand why it would make an issue like this but it works. Thanks for the help.
