### ISSUE TITLE
Cirtical error in "WC-Rechnungen >> Rechnungen"

### ISSUE THREAD

**Issue by postme24** [ole1986/wc-invoice-pdf#19]
Hi Ole,

arbeite mit WP 5.3.2 / WC 3.9.2 und demnächst mit WC 4.x . Es scheint, als wenn das Plugin noch nicht kompatibel ist, wird es denn aufgrund der geringen Installationen überhaupt noch supported?

Dank & Gruß, J.

**Comment by ole1986** [comment]
Hi,

it does support WP 5.3.2 with WC 3.9.2. It would be helpful to have detailed info about the error.
You may checkout the PHP error log while opening the the "WC-Invoice" setting and post it here

**Comment by ole1986** [comment]
@postme24 could you figure out the error details? 

The following link may be helpful to find your error log:
https://www.geeksforgeeks.org/where-does-php-store-the-error-log-php5-apache-fastcgi-cpanel/

Also it can provide us with additional info on what php modules are being loaded (and maybe causing the error)

**Comment by postme24** [comment]
..sure, here it goes. I hope it helps, thank you.

2020-03-02T09:54:33+00:00 CRITICAL Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php:120
Stack trace:
#0 /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php(120): DateTimeZone->__construct('')
#1 /var/www/vhosts/domain.com/httpdocs/wp-includes/class-wp-hook.php(288): WCInvoicePdf\Menu\InvoiceMenu->DisplayInvoices('')
#2 /var/www/vhosts/domain.com/httpdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#3 /var/www/vhosts/domain.com/httpdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /var/www/vhosts/domains.com/httpdocs/wp-admin/admin.php(254): do_action('wc-rechnungen_p...')
#5 {main}
  thrown in /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php on line 120

**Comment by ole1986** [comment]
This issue has already been resolved in #18 
You may change the timezone to something that is supported by PHP
https://github.com/ole1986/wc-invoice-pdf/issues/18#issuecomment-570649709

**Comment by ole1986** [comment]
Also it would be interessting which timezone has previously been defined which caused that error
Thank you in advanced!

**Comment by postme24** [comment]
..cool! I'll contact my hoster to solve this bug.

**Comment by postme24** [comment]
..strange! I changed the time settings in WordPress from UTC+1 to Berlin and everything works fine. I've seen the comment from lonerunner ( #18 ).

Thanks a lot, cool plugin, it is exactly what I am looking for.. :)

**Comment by ole1986** [comment]
Good to know that you have fixed it.

**Comment by postme24** [comment]
..one thing I've seen right now. I think the plugin is not usable in Germany in this form because it add tax to a net price. Everyone in Germany who sells to end customers ( B2C ) has to show a price that is inclusive and not exclusive tax ( VAT ). Sure, the tax can be shown on the invoice. But the total cost must include tax.

And it seems there is another bug. If I try to generate an invoice there happen nothing. No invoice, no button to download, no error message, nothing, sorry Ole..

**Comment by ole1986** [comment]
Nothing to sorry about. 

Please do me a favor and divide the issues properly otherwise with loosing track on it.
Regarding the tax inclusive issue I think can be an option from the settings (or per order) to either include or exclude the tax.

But again, please issue it properly. 
Thank you
