### ISSUE TITLE
Kann es im WP-Admin leider nicht finden

### ISSUE THREAD

**Issue by yunse1** [ole1986/wc-invoice-pdf#2]
Hallo Ole :)
Kann den Punkt WC-Invoices leider im WP-Admin nicht finden, um die Einstellungen vorzunehmen. Geht dein Plugin noch? Brauch unbedingt ein Plugin für Sammelrechnungen. Danke!

**Comment by ole1986** [comment]
Hallo,

um dir weiter zu helfen benötige ich einige Details zu deinem Setup.
Welche wordpress version wird denn verwendet?

**Comment by yunse1** [comment]
Hallo Ole, 
alles auf dem neusten Stand. Wordpress 5.0. Aber ich bemerke gerade mit deinem Plugin kann man keine Sammelrechnungen machen oder? Sondern nur wiederkehrende Rechnungen?

**Comment by ole1986** [comment]
Korrekt - Sammelrechnungen sind so nicht möglich. Das plugin legt den Schwerpunkt auf sogenannte "recurring" (wiederkehrende) Rechnungen die über den wp-cron job entsprechend getriggert und automatisiert an den Kunden übermittelt wird.

Vielleicht können wir deine Anforderungen eines Tages mit implementieren.
Vorerst ist es allerdings nicht dafür vorgesehen.

Tut mir Leid!
