### ISSUE TITLE
removes product price field from all product types

### ISSUE THREAD

**Issue by xllentech** [ole1986/wc-invoice-pdf#22]
Hi, When this plugin is installed, it removes regular price and sale price from all product types and it's visible only on Working hours product type. See screenshots.

I think it's not right, All other product types should still have the price tab visible. 

let me know if that's how you think it should be.

Thank you for your free plugin.

![wc-invoice-pdf-issue1](https://user-images.githubusercontent.com/20546464/76001848-f678ce00-5ec2-11ea-8c28-4a44bfeaaf71.jpg)
![wc-invoice-pdf-issue2](https://user-images.githubusercontent.com/20546464/76001861-fbd61880-5ec2-11ea-8d86-bbec502f38b5.jpg)

Thank you ..

**Comment by ole1986** [comment]
Thank you for reporting... will fix this asap
