### ISSUE TITLE
Tutorial for wc-invoice and wp-ispconfig-3

### ISSUE THREAD

**Issue by smilebasti** [ole1986/wc-invoice-pdf#23]
Hi, is there a documentation how to set up this the right way? Or maybe even a tutorial?

**Comment by ole1986** [comment]
Unfortunately not, yet..
May I help you with something?

Trying to add a tutorial soon into a wiki page

**Comment by smilebasti** [comment]
Ok thanks. A wiki would help very much.

I have seen on the plugin screenshots that there was under settings of wc invoice, under ISPConfig client template a custom one. I can only choose: None. 

I think that would help me for the beginning. 
Thanks for the quick response. Till now the two plugins look very promising :)

**Comment by ole1986** [comment]
Just published a quick guide for interacting with WP Ispconfig3
https://github.com/ole1986/wc-invoice-pdf/wiki/Interacting-with-WP-ISPConfig3

**Comment by ole1986** [comment]
@smilebasti you may need to configure the WP-ISPConfig3 plugin first.

Checkout the following for configuring WP-ISPConfig3 together with ISPConfig:
https://wordpress.org/plugins/wp-ispconfig3/#installation

**Comment by ole1986** [comment]
Client Templates are known to be the Limit Templates in ISPConfig

![image](https://user-images.githubusercontent.com/4850116/76257134-62f02600-6251-11ea-8c36-e85628ed0e33.png)

**Comment by smilebasti** [comment]
Super thanks a lot

**Comment by ole1986** [comment]
As a side note, client templates are not required as far as I remember

**Comment by smilebasti** [comment]
Ok then maybe you can help to find how i can create different sized Webspaces as different Products in Woocommerce? Or did i misunderstood the plugin?
I would like to sell different Webspace packages for different prices. Is this possible with your plugin?
Or do i have to use the ISPConfig Blocks/Fields after the costumer bought something in the shop on a new page?
Thanks

**Comment by ole1986** [comment]
You are hitting the exact point. 

At the moment only webspace is supported and only the the Client limit template (defined in the WC-Invoice -> Settings -> Orders) is taken into account.

I think I can quickly provide an option from inside the "Webspace" product allowing you to override client template quotas and possible other options (like SSL, PHP, ....)

**Comment by ole1986** [comment]
Something similar to this:

![image](https://user-images.githubusercontent.com/4850116/76355541-c727ee00-6314-11ea-8a54-8728778a12d3.png)

**Comment by smilebasti** [comment]
Wow super. Thank you very much. Looking forward for thr future development :)

**Comment by smilebasti** [comment]
Hi, just wanting to ask when you are planning to publish this feature?
Thanks

**Comment by ole1986** [comment]
This weekend!
