### ISSUE TITLE
Synchronized password creation

### ISSUE THREAD

**Issue by smilebasti** [ole1986/wc-invoice-pdf#29]
Hi, i am using this plugin for ispconfig. The method i am using for registering is not the Ipsconfig Blocks but the Product (Webspace). During check-out it creates a Wordpress/woocommerce Account and an ISPConfig account but with different passwords.

Is there a way to hand out the same password ? 
Or to send the Welcome Mail from the ISPConfig Mail Template with the set password?
(Currently it only sends this welcome mail when i manually register a new user)

Thanks in advance

**Comment by ole1986** [comment]
Unfortunately it cannot simply apply the same password from it's WordPress account into ISPConfig because the password is only available as hash. Passing the hash is no option to set a password in ISPConfig.

The WP-Ispconfig plugin provides an option to "sync" the password with the same account from ISPConfig (if username matches) whenever the user changes it through WordPress

The below link may be helpful

https://github.com/ole1986/wp-ispconfig3/issues/31#issuecomment-555139407

**Comment by smilebasti** [comment]
Ok thanks.

**Comment by smilebasti** [comment]
I now tried to change the password in the Wordpress Frontend after i used my way of registering the new user.
Do i have to use the WP-Ispconfig Block for registering the new User for the Password-sync to work or is this a Bug?

**Comment by smilebasti** [comment]
Sorry for asking again but do i have to use the ISP-Config 3 Blocks to register new users, that the synchronization is working of the passwords?
 
Thanks for your great plugin

**Comment by ole1986** [comment]
actually it should sync the password with ispconfig3 clients once the customer changes the password of the wordpress account (through the woocommerce hook "woocommerce_customer_reset_password").

This hook is being used in under /my-account/edit-account provided by the woocommerce form (frontend). For the storefront theme the woocommerce "my account" -> "Passsword change" section may look similar to this:

![image](https://user-images.githubusercontent.com/4850116/77946961-724c1780-72c3-11ea-9513-e1fc4c13d83c.png)

See: https://github.com/ole1986/wp-ispconfig3/blob/master/index.php#L108

**Comment by smilebasti** [comment]
I have tried it now a couple of times and every time it created a Wordpress Account and a Ispconfig account but when i change the password in the Wordpress frontend (as you described) it is not synchronizing with ispconfig. 
I am not sure what to do tell you more? Are there logs of your plugin?

**Comment by smilebasti** [comment]
Hi, i now tried creating the new user with the ispconfig block. In this case i am getting the same passwords in wordpress and ispconfig. After this i tried to change the password in the Wordpress/WooCommerce frontend as you are showing on the picture above. This is not working for me. The password changes in wordpress but not in ispconfig. 
I would like to help solve this problem... I am using the newest Woocommerce and the newest Wordpress.
Is there a way to narrow down the error? Are there somewhere logs?
Thanks

**Comment by ole1986** [comment]
I have double checked it.
Please make sure the following applies to your setting

* Enable `WP-ISPConfig 3` -> `Settings` -> `User Mapping` -> `Enable password syncronization`
* Make sure `WP-ISPConfig 3` -> `Settings` -> `User Mapping` -> `User roles being used to match the clients stored in ISPConfig3` matches the roles the password should be synced
* Also make sure the username in Wordpress exactly matches the ISPConfig client username
* Change the password using https://yourdomain/my-account/ from the `Account details`

Successfully tested on Wordpress 5.4 with Woocommerce 4.0.1 using WP User "test" which was also located in ISPConfig Clients

**UPDATED**

Please also make sure the SOAP connection is properly defined in `WP-ISPConfig 3` -> `Settings` -> `SOAP Settings`

**Comment by smilebasti** [comment]
Thanks for you patience.
I have offerlooked the button to sync the passwords. My mistake
