### ISSUE TITLE
Upfront payment notification and different recurring per product

### ISSUE THREAD

**Issue by lonerunner** [ole1986/wc-invoice-pdf#3]
Hello, i know that there is explanation how to use it, and basically if you want to make product payment automatically per yearly there is code 

`
do_action('wcinvoicepdf_order_period', $order_id, 'yearly');
`

But can i make it different per product, so one product is paid yearly and another product is paid monthly.

And also when invoice is generated it's generated on day of purchase and user have 2 weeks to make payment, but i want user to make paid prepaid, so next invoice to be generated upfront and notify user 2 weeks before expiration, kinda like when you buy domain and next year you get 30 days upfront notification for payment.

**Comment by ole1986** [comment]
There is a product type called Website which allows the customer to either select yearly or monthly payment.

But I agree to the idea of having an option which locks the product from either using yearly or monthly periods. I may add this to the next update.

-- 

Regarding your other question it sounds more like a subscription then a recurring payment.
What I always want to include is a proper recurring payment (through paypal) which auto-generate the next invoice (for the next upcoming period) while charging the amount from the account.
