### ISSUE TITLE
Fatal error Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by JUSSKiE** [ole1986/wc-invoice-pdf#34]
Hi Guys,

When trying to use with plugin WooCommerce 5.2.2 / Wordpress 5.7.1 I'm getting the following:

Fatal error: Uncaught Error: Class 'NumberFormatter' not found
in /home/----/----/wp-content/plugins/wc-invoice-pdf/model/invoice-pdf.php on line 28

This is happening when trying to generate an invoice.

Thanks,

**Comment by ole1986** [comment]
Please make sure you have enabled the intl extension for PHP.
More details here: https://stackoverflow.com/questions/30554177/fatal-error-class-numberformatter-not-found/42893929
