### ISSUE TITLE
date confusion

### ISSUE THREAD

**Issue by dme1sc** [ole1986/wc-invoice-pdf#36]
Hi, I am working with your invoice tool for recurring invoices.  I'm trying to figure out the date functions.  I create an invoice in woo using a create date in the future (example 2022-06-01) then generate the schedule with your tool.  The script then provides the summary list showing today's create date and a due date two weeks from now.  

What decides this due date?  It doesn't appear to be any function I can manipulate in the settings.

What are the functions of B2C or Offer supposed to provide? When I tick B2C, I don't see any noticeable changes anywhere.  When I press Offer, it appears to provide a pdf popup that appears to be identical to the Preview button.  

Thanks.  I do like this script.  To make it work for me, it appears I have to create the invoice on the days I want them due over the next year and then make them recurring at that time.  I'd prefer to build them all now and date them for the future and schedule them for the future.

**Comment by dme1sc** [comment]
any feedback here?  is this project still alive?

**Comment by ole1986** [comment]
I pretty much hard code due to german billing concepts.
But whenever such request is appearing here I am trying to get things improved to be more flexible

**Comment by dme1sc** [comment]
If you can point me in the general direction, I can get my dev to look at it.  Thansk
Doug

**Comment by ole1986** [comment]
B2C = Business to Custom
When you hook the B2C the invoice is calculated differently (customer friendly)

**Without B2C - Taxes are excluded in the item**
![image](https://user-images.githubusercontent.com/4850116/169562249-015a4e3c-81b2-47d4-9c7f-4d4f0b1f8555.png)

**With B2C - Taxes are included in the item**
![image](https://user-images.githubusercontent.com/4850116/169562422-d7be033b-24e8-4b40-8941-4facac1acaff.png)

**Comment by ole1986** [comment]
In the upcoming version the PR #38 there will also be an option to configure the due date globally (default: 14 days)
