### ISSUE TITLE
Error 500 when enable "Automative invoice submission"

### ISSUE THREAD

**Issue by csib** [ole1986/wc-invoice-pdf#4]
To get this error:
Enable Automative invoice submission om "Settings" - > "Task scheduler", then try to open the "Invoices".

Result: error 500.

Its nginx+php-fpm 7.3

Log is attached.

I think it's relates also to this issue, but tried the WooCommerce integration, ordered a webhosting, then, set it's state to proccessing, then completed, but nothing happened in ISPConfig. The user/website isn't created.

Update: In WP core, these were another TimeZone, then my real timezone, which caused this.After I've set it to my real TZ the invoices menu is working. But the creation in ISPConfig still not happens.

If I press "Invoice" on WooCommerce orders ->Edit order it writes Invoice 201909-4317-R created in order notes, but I can't find the invoice in WC-Invoices -> Invoices, still empty.

[wc-invoice.txt](https://github.com/ole1986/wc-invoice-pdf/files/3665822/wc-invoice.txt)

**Comment by ole1986** [comment]
It seem to be an SQL error accessing the wp_users. This may have something to do with the installation or definition of the database table prefixes.

According to your log output, it uses two different tables prefixes

`wpy_` to open the table `wpy_ispconfig_invoice` - see [account-invoice.php on line 36](https://github.com/ole1986/wc-invoice-pdf/blob/061e7e61150b9c2512750de9eb0f0873e5955798/menu/account-invoice.php#L36)
and `wp_` to open all the others.

Can you explain me the two different prefixes in your wordpress setup?

**Comment by csib** [comment]
I can't explain it. When I have initialized the database I've set the prefix to wpy_ so this is valid. All other prefixes shouldn't exists.

I think you are using default prefix in your code, which is okay, for websites, which using default wp_ prefix.
Update: I can confirm this. It's bug.

Update2: I've fixed it locall in my WP. There is no problem now. I can list the invoices, but after I set an invoice to Paid, still not created the website in ISPConfig

**Comment by ole1986** [comment]
@csib this issue should be resolved in version 1.4.4

**Comment by csib** [comment]
Thank you.

Maybe you should update this too:
https://github.com/ole1986/wc-invoice-pdf/blob/master/model/invoice.php#L287

After order a product in Woo and paid it, the domain/site should be created in ISP, but in my case it should not happen. Can't find any code which doing this. Or after this it is not yet implemented?

**Comment by ole1986** [comment]
Why do you think a paid invoice cause another plugin (the wp-ispconfig plugin) to create the user.

**Comment by csib** [comment]
Good question. I tought that you have created this plugin to work with the wp-ispconfig plugin together. So in my mind this means after subscribtion the user is created with the wp-ispconfig plugin. This is a good FR I think.

This misunderstood came from the readmes:
`**For WooCommerce integration, please consider installing the [WC Recurring Invoice PDF](https://wordpress.org/plugins/wc-invoice-pdf/) plugin (v1.4)**`

And from the wc-invoice's readme:

`== Installation ==

* Search for "wp-ispconfig3" in the "Plugins -> Install" register
* Install and active the plugin
* Open the "WC-Invoices" -> "Settings" menu from admin pane for configuration`

Yor installation proccess is starts with install wp-ispconfig3 which means for me they are working together, but they are totally independent.

**Comment by ole1986** [comment]
It actually does. But the focus is on recurring invoices...

So for example you create an order you can setup the period (monthly / yearly). Once this is configured a schedule will check the intervals and generate and email the invoice automatically to customers email address.

If no recurring is enabled you have the option to create the invoice manually using the "invoice" button from the "edit order" page. Once you pressed the button you will see the invoice in the invoice list.

**Comment by ole1986** [comment]
I really would like to have more automated in relation to the wp-ispconfig3 plugin.

And whenever I have time I will do so.

Sorry that it does not fully match your requirements yet.
