### ISSUE TITLE
Should allow checkout completion even if a domain is already registered or cannot be verified

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#5]
# Current Problem:

- If you try to checkout with a domain that has already been registered, you won't be allowed to proceed and will be give an "The domain is already registered" error. This stops anyone who wants to move their existing domain to you from proceeding with checkout. 
- Also if one wanted to a TLD such as .co.zw (which is not supported by the WC-Invoice check), they they get an "The domain could not be verified" error. 

# Proposed Solution

 When a domain is entered, we should only check if it's already in the ISPConfig server. If not, we should allow the buyer to proceed with checkout. A domain that is already registered or that cannot be verified should not stop us from proceeding with checkout.

**Comment by ole1986** [comment]
wc-invoice-pdf actually uses the wp-ispconfig3 plugin to verify the domains (through ajax).

I think I will give wp-ispconfig3 plugin an option to only check domain only against ISPConfig (hooked/unhooked)

Pingback: https://github.com/ole1986/wp-ispconfig3/issues/24
