### ISSUE TITLE
Uncaught Exception: DateTimeZone::__construct():

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wc-invoice-pdf#9]
I'm getting the following bug when I visit the /admin.php?page=wcinvoicepdf_invoices URL

```
An error of type E_ERROR was caused in line 112 of the file /wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php. Error message: Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php:112
Stack trace:
#0 /wp-content/plugins/wc-invoice-pdf/menu/invoice-menu.php(112): DateTimeZone->__construct('')
#1 /wp-includes/class-wp-hook.php(286): WCInvoicePdf\Menu\InvoiceMenu->DisplayInvoices('')
#2 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /wp-admin/admin.php(253): do_action('wc-invoices_pag...')
#5 {main}
  thrown
```

**Comment by ole1986** [comment]
@tkembo Which version are you using?

**Comment by tawandakembo** [comment]
I'm on Version 1.4.7

**Comment by ole1986** [comment]
Can you please check your database table `wp_options` for the option_name `timezone_string` and let me know the value?

**Comment by tawandakembo** [comment]
there is no timezone_string in the table. There is only time_format and date_format. Could that be the reason?

**Comment by ole1986** [comment]
Yes, this is the reason. It does not check for any default value. So timezone "" is invalid.
As a workaround you can save a timezone from the wordpress settings page matching one of [those in the list](https://www.php.net/manual/de/timezones.php)

Alternatively I am going to patch this in the next version 1.5.0

**Comment by tawandakembo** [comment]
thank you. this was very helpful.
Out of interest, when can we expect version 1.5.0 to come out?

**Comment by ole1986** [comment]
Since v1.5.0 is only a compatibility update to [wp-ispconfig3](https://github.com/ole1986/wp-ispconfig3/releases/tag/1.4.3) it may happen very soon
